// <auto-generated />
namespace test1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class trainar_one1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(trainar_one1));
        
        string IMigrationMetadata.Id
        {
            get { return "201703241058308_trainar_one1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
